### ISSUE TITLE
Some weird error I don’t understand

### ISSUE THREAD

**Issue by Ermmwhatflip** [VyperGroup/astroidv3#26]
Okay so every time I use something Nowgg related it pops up with this error: Error: write EPROTO C0F742CF1B7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:

**Comment by FatGrizzly** [comment]
will be up soon

**Comment by Ermmwhatflip** [comment]
k thanks
